### ISSUE TITLE
balnk page on call reports page with graph

### ISSUE THREAD

**Issue by jcattan** [Star2Billing/a2billing#100]
Hi everybody,
i've a2billing 2.1.0 on asterisk 11 
i'v about 150 000 call per day (20 000 per hours) and the graphs on the 'compare calls' and 'daily traffic' pages do a full blank page if i select my big customers . it work perfect if i filter a little on
i think there is a limmit in the graphs but i don't see it in the php pages
can you help me please

**Comment by ultratone** [comment]
increase your php memory limit in php.ini

memory_limit = 512M

--

UltraTone Sdn Bhd

*United States Office: *75 East Santa Clara Street, Suite P-80, San Jose,
95113

Phone: +1-408-715-2002

Fax:   +1-408-459-7766

Cell:  +1-818-910-2001


*Malaysia Office: *Unit 17A, Plaza Ampang City, No 332A Jalan Ampang,  KL,
50450

Phone: +60-3-2730-6404

Fax:   +60-3-48138823

Cell:  +60-12-3919138


*Websites: *UltraTone.com.my <http://www.ultratone.com.my/>


<http://www.ultratone.com.my/>

**Comment by jcattan** [comment]
YES !!!!
i put 1024M in php.ini and it's work verry nice
thank you very much
