### ISSUE TITLE
Blank page after installing latest version of a2billing

### ISSUE THREAD

**Issue by gudge25** [Star2Billing/a2billing#104]
[Thu May 28 19:02:36 2015] [error] [client 134.249.181.77] PHP Warning:  require_once(/var/www/html/a2billing/common/lib/../../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/a2billing/common/lib/admin.defines.php on line 33
[Thu May 28 19:02:36 2015] [error] [client 134.249.181.77] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/a2billing/common/lib/../../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/a2billing/common/lib/admin.defines.php on line 33

 
---SEEMS there is no such  file at all

**Comment by redge76** [comment]
Same issue. Certainly due to composer.

**Comment by helsinki** [comment]
Оr just use SVN version. It is not messed up yet.

**Comment by areski** [comment]
there is still a SVN version :)

**Comment by ultratone** [comment]
Is the a SVN trunk of A2billing to download?

--

UltraTone Sdn Bhd

*United States Office: *75 East Santa Clara Street, Suite P-80, San Jose,
95113

Phone: +1-408-715-2002

Fax:   +1-408-459-7766

Cell:  +1-818-910-2001


*Malaysia Office: *Unit 17A, Plaza Ampang City, No 332A Jalan Ampang,  KL,
50450

Phone: +60-3-2730-6404

Fax:   +60-3-48138823

Cell:  +60-12-3919138


*Websites: *UltraTone.com.my <http://www.ultratone.com.my/>


<http://www.ultratone.com.my/>

**Comment by pcdrob123** [comment]
Hi,
Did anyone manage to fix this issue as im experiencing the same problem. I have installed the composer but doesnt make any difference.

**Comment by tsromana** [comment]
@pcdrob123 try to explode the tar instead of pulling the git worked for me this way

**Comment by pcdrob123** [comment]
@tsromana  where would i get the tar from

**Comment by tsromana** [comment]
https://codeload.github.com/Star2Billing/a2billing/tar.gz/v2.1.0

**Comment by gudge25** [comment]
I done there was a problem with link in tar archive.
Tomorrow will give u more inf.meanwhile check broken links in folder of a2b

**Comment by redge76** [comment]
you have to link the source a2billing source directory to the http server directory. (not copy the files !)
You also have to use the apache FollowSymLinks option .
redge

**Comment by icaxis** [comment]
Even with Symlinks, it doesn't work... I check for the folder vendor and it seems it doesn't exist at all nor for the file autoload.
Did anyone solve this or able to workaround.?

**Comment by redge76** [comment]
Did you run:

cd /usr/local/src/a2billing   (or where you have the source....)

curl -sS https://getcomposer.org/installer | php

php composer.phar update

php composer.phar install



Then ..



mkdir /var/www/html/a2billing

ln -s /usr/local/src/a2billing/common /var/www/html/a2billing/common

ln -s /usr/local/src/a2billing/admin /var/www/html/a2billing/admin

ln -s /usr/local/src/a2billing/agent /var/www/html/a2billing/agent

ln -s /usr/local/src/a2billing/customer /var/www/html/a2billing/customer



chown -R asterisk:asterisk /var/www/html/a2billing

chown -R asterisk:asterisk /usr/local/src/a2billing



chmod 755 /var/www/html/a2billing/admin/templates_c
chmod 755 /var/www/html/a2billing/customer/templates_c
chmod 755 /var/www/html/a2billing/agent/templates_c

**Comment by icaxis** [comment]
Thanks redge76, It works for me.

**Comment by catchcoin** [comment]
i did that bit it not worked could you help me my skype is jasaroc

**Comment by afshin-blue** [comment]
fixed and worked through this process
i installed v2.1.2 from https://codeload.github.com/Star2Billing/a2billing/tar.gz/v2.1.2
got this error: PHP Fatal error: require_once(): Failed opening required '/var/www/html/a2billing/common/lib/../../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/a2billing/common/lib/admin.defines.php on line 33
used composer then error gone and got two new error:
PHP Parse error:  syntax error, unexpected '[' in /usr/local/src/a2billing/common/lib/Misc.php on line 1290
PHP Parse error:  syntax error, unexpected '[' in /usr/local/src/a2billing/common/lib/Misc.php on line 1302 
then removed [1]
site came up. still this error unexpected '[' exist in 2.1.2

**Comment by NogieGit** [comment]
Having the same problem as afshin-blue.. I installed v2.1.2 also

**Comment by areski** [comment]
which php version are you running?

**Comment by NogieGit** [comment]
Hi,

I am running CentOS 6.6
and php-5.3.3-46.el6_6.x86_64.

Error I am getting is 

 PHP Warning:  require_once(/var/www/html/a2billing/common/lib/../../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/a2billing/common/lib/admin.defines.php on line 33
[Tue Jul 28 02:35:46 2015]  PHP Fatal error:  require_once(): Failed opening required '/var/www/html/a2billing/common/lib/../../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/a2billing/common/lib/admin.defines.php on line 33

Thanks

**Comment by NogieGit** [comment]
Areski,

Any updates?

**Comment by catchcoin** [comment]
no
there was many other errors.

2015-07-29 11:33 GMT-03:00 Nogie Ekunwe <notifications@github.com>:

> Areski,
>
> Any updates?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Star2Billing/a2billing/issues/104#issuecomment-125970884>
> .
>



-- 
Jasar orion Cirelli
----------------------------------
Contato:
email:   jasaroc@gmail.com
skype:  jasaroc
Cel:      (11) 986435771  ( TIM )

**Comment by NogieGit** [comment]
Please point me in the right direction. Thanks

**Comment by areski** [comment]
I have the feeling there is something wrong with PHP version, I m going to try now on an centos 6.5

**Comment by catchcoin** [comment]
ok tank you

2015-07-29 12:18 GMT-03:00 Areski Belaid <notifications@github.com>:

> I have the feeling there is something wrong with PHP version, I m going to
> try now on an centos 6.5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Star2Billing/a2billing/issues/104#issuecomment-125985614>
> .
>



-- 
Jasar orion Cirelli
----------------------------------
Contato:
email:   jasaroc@gmail.com
skype:  jasaroc
Cel:      (11) 986435771  ( TIM )

**Comment by NogieGit** [comment]
Hello,

I see a trailing dot when I issue ls -l. Could this possibly be the culprit?

See below
drwxr-xr-x  6 root root 4096 Jul 25 01:23 a2billing
drwxr-xr-x. 2 root root 4096 Oct 16  2014 cgi-bin
drwxr-xr-x. 3 root root 4096 Jul 15 05:29 error
drwxrwxrwx. 3 root root 4096 Jul 25 01:43 html
drwxr-xr-x. 3 root root 4096 Jul 15 05:30 icons


Thx

**Comment by catchcoin** [comment]
leave it :( i will use 2.5 version of elastix
tanks for help

2015-07-29 12:39 GMT-03:00 Nogie Ekunwe <notifications@github.com>:

> Hello,
>
> I see a trailing dot when I issue ls -l. Could this possibly be the
> culprit?
>
> See below
> drwxr-xr-x 6 root root 4096 Jul 25 01:23 a2billing
> drwxr-xr-x. 2 root root 4096 Oct 16 2014 cgi-bin
> drwxr-xr-x. 3 root root 4096 Jul 15 05:29 error
> drwxrwxrwx. 3 root root 4096 Jul 25 01:43 html
> drwxr-xr-x. 3 root root 4096 Jul 15 05:30 icons
>
> Thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Star2Billing/a2billing/issues/104#issuecomment-125992725>
> .
>



-- 
Jasar orion Cirelli
----------------------------------
Contato:
email:   jasaroc@gmail.com
skype:  jasaroc
Cel:      (11) 986435771  ( TIM )

**Comment by pcdrob123** [comment]
Hi
I would be more than happy to fix this 

Add me Skype. Threedtelecoms

**Comment by catchcoin** [comment]
rsss me to but my client have a operational elastix 2.5 and he doesnt want
MT any more due this problems

2015-07-29 12:42 GMT-03:00 pcdrob123 <notifications@github.com>:

> Hi
> I would be more than happy to fix this
>
> Add me Skype. Threedtelecoms
> > On 29 Jul 2015, at 16:39, Nogie Ekunwe <notifications@github.com>
> Iwrote:
> >
> > Hello,Lll
> >
> > I see a trailing dot when I issue ls -l. Could this possibly be the
> culprit?
> >
> > See below
> > drwxr-xr-x 6 root root 4096 Jul 25 01:23 a2billing
> > drwxr-xr-x. 2 root root 4096 Oct 16 2014 cgi-bin
> > drwxr-xr-x. 3 root root 4096 Jul 15 05:29 error
> > drwxrwxrwx. 3 root root 4096 Jul 25 01:43 html
> > drwxr-xr-x. 3 root root 4096 Jul 15 05:30 icons
> >
> > Thx
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Star2Billing/a2billing/issues/104#issuecomment-125993643>
> .
>



-- 
Jasar orion Cirelli
----------------------------------
Contato:
email:   jasaroc@gmail.com
skype:  jasaroc
Cel:      (11) 986435771  ( TIM )

**Comment by pcdrob123** [comment]
MT?

Here to help if required

**Comment by NogieGit** [comment]
@pcdrob123 Please help

**Comment by catchcoin** [comment]
tank you for help :D

2015-07-29 12:54 GMT-03:00 Nogie Ekunwe <notifications@github.com>:

> @pcdrob123 <https://github.com/pcdrob123> Please help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Star2Billing/a2billing/issues/104#issuecomment-125997282>
> .
>



-- 
Jasar orion Cirelli
----------------------------------
Contato:
email:   jasaroc@gmail.com
skype:  jasaroc
Cel:      (11) 986435771  ( TIM )

**Comment by pcdrob123** [comment]
Can you add me on Skype to communicate better

**Comment by catchcoin** [comment]
sure my skype is jasaroc

2015-07-29 13:05 GMT-03:00 pcdrob123 <notifications@github.com>:

> Can you add me on Skype to communicate better
>
> > On 29 Jul 2015, at 16:54, Nogie Ekunwe <notifications@github.com> wrote:
> >
> > @pcdrob123 Please help
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Star2Billing/a2billing/issues/104#issuecomment-126000912>
> .
>



-- 
Jasar orion Cirelli
----------------------------------
Contato:
email:   jasaroc@gmail.com
skype:  jasaroc
Cel:      (11) 986435771  ( TIM )

**Comment by areski** [comment]
after some testing on CentOS6, I just pushed a patch https://github.com/Star2Billing/a2billing/commit/a1beacb5c0bfa101c599bbe110b1f3fee5cf7245 

Make sure you have php-xml installed and that you install vendor packages with compose:
    cd /usr/local/a2billing
    curl -sS https://getcomposer.org/installer | php
    php composer.phar update
    php composer.phar install

That should do the trick

**Comment by NogieGit** [comment]
Hello Areski,

 

I am running php-5.3.3-46.el6_6.x86_64 on CentOS 6.6

 

Thanks

 

 

---------------------------
Nogie Ekunwe
EDO Network Services, Inc.
P O Box 20243
Jackson, MS 39289
+1.601.313.9009(P)

+1.601.497.3932(C)
+1.601.313.9009(F)

---------------------------

*********************************************************************************

IMPORTANT.This e-mail message and any attachments are strictly confidential and may be protected by law. This message is intended only for the named recipient(s) above.
If you have received this message in error, or are not the named recipient(s), please notify the sender and delete this e-mail message immediately.
Any unauthorized view, usage or disclosure of this message or information therein is prohibited.
E-mail messages may in general be unreliable, EDO Network Services, Inc. shall not be liable for any message if modified, changed or falsified. The recipient should ensure that this email message is virus free before they open or view it.

*********************************************************************************

**Comment by miken32** [comment]
As this requirement for Composer is a fairly big change, it might be worthwhile putting a check in place, so that if autoload.php can't be included, it shows an error message. Over the last few years I think everyone has gotten used to just untarring over the old version and updating the database.

**Comment by joemamo** [comment]
Hi,

After following the setup instructions I tried to make a call but the call is answered and hungup without any enter your pin number announcement. 

This is probably not the right location to post this kind of question but didn't know where to ask.

Here is the log which includes the a2billing log as well:


  == Using SIP RTP TOS bits 184
  == Using SIP RTP CoS mark 5
    -- Executing [17772295467@from-pstn:1] Set("SIP/callcentric15-00000002", "__FROM_DID=17772295467") in new stack
    -- Executing [17772295467@from-pstn:2] Gosub("SIP/callcentric15-00000002", "sub-record-check,s,1(in,17772295467,dontcare)") in new stack
    -- Executing [s@sub-record-check:1] GotoIf("SIP/callcentric15-00000002", "0?initialized") in new stack
    -- Executing [s@sub-record-check:2] Set("SIP/callcentric15-00000002", "__REC_STATUS=INITIALIZED") in new stack
    -- Executing [s@sub-record-check:3] Set("SIP/callcentric15-00000002", "NOW=1440300079") in new stack
    -- Executing [s@sub-record-check:4] Set("SIP/callcentric15-00000002", "__DAY=22") in new stack
    -- Executing [s@sub-record-check:5] Set("SIP/callcentric15-00000002", "__MONTH=08") in new stack
    -- Executing [s@sub-record-check:6] Set("SIP/callcentric15-00000002", "__YEAR=2015") in new stack
    -- Executing [s@sub-record-check:7] Set("SIP/callcentric15-00000002", "__TIMESTR=20150822-202119") in new stack
    -- Executing [s@sub-record-check:8] Set("SIP/callcentric15-00000002", "__FROMEXTEN=unknown") in new stack
    -- Executing [s@sub-record-check:9] Set("SIP/callcentric15-00000002", "__MON_FMT=wav") in new stack
    -- Executing [s@sub-record-check:10] NoOp("SIP/callcentric15-00000002", "Recordings initialized") in new stack
    -- Executing [s@sub-record-check:11] ExecIf("SIP/callcentric15-00000002", "0?Set(ARG3=dontcare)") in new stack
    -- Executing [s@sub-record-check:12] Set("SIP/callcentric15-00000002", "REC_POLICY_MODE_SAVE=") in new stack
    -- Executing [s@sub-record-check:13] ExecIf("SIP/callcentric15-00000002", "0?Set(REC_STATUS=NO)") in new stack
    -- Executing [s@sub-record-check:14] GotoIf("SIP/callcentric15-00000002", "2?checkaction") in new stack
    -- Goto (sub-record-check,s,17)
    -- Executing [s@sub-record-check:17] GotoIf("SIP/callcentric15-00000002", "1?sub-record-check,in,1") in new stack
    -- Goto (sub-record-check,in,1)
    -- Executing [in@sub-record-check:1] NoOp("SIP/callcentric15-00000002", "Inbound Recording Check to 17772295467") in new stack
    -- Executing [in@sub-record-check:2] Set("SIP/callcentric15-00000002", "FROMEXTEN=unknown") in new stack
    -- Executing [in@sub-record-check:3] ExecIf("SIP/callcentric15-00000002", "11?Set(FROMEXTEN=12063700000)") in new stack
    -- Executing [in@sub-record-check:4] Gosub("SIP/callcentric15-00000002", "recordcheck,1(dontcare,in,17772295467)") in new stack
    -- Executing [recordcheck@sub-record-check:1] NoOp("SIP/callcentric15-00000002", "Starting recording check against dontcare") in new stack
    -- Executing [recordcheck@sub-record-check:2] Goto("SIP/callcentric15-00000002", "dontcare") in new stack
    -- Goto (sub-record-check,recordcheck,3)
    -- Executing [recordcheck@sub-record-check:3] Return("SIP/callcentric15-00000002", "") in new stack
    -- Executing [in@sub-record-check:5] Return("SIP/callcentric15-00000002", "") in new stack
    -- Executing [17772295467@from-pstn:3] Set("SIP/callcentric15-00000002", "CDR(did)=17772295467") in new stack
    -- Executing [17772295467@from-pstn:4] ExecIf("SIP/callcentric15-00000002", "1 ?Set(CALLERID(name)=12063700000)") in new stack
    -- Executing [17772295467@from-pstn:5] Set("SIP/callcentric15-00000002", "CHANNEL(musicclass)=default") in new stack
    -- Executing [17772295467@from-pstn:6] Set("SIP/callcentric15-00000002", "__MOHCLASS=default") in new stack
[2015-08-22 20:21:19] WARNING[5101][C-00000002]: func_channel.c:560 func_channel_read: Unknown or unavailable item requested: 'reversecharge'
    -- Executing [17772295467@from-pstn:7] GotoIf("SIP/callcentric15-00000002", "0?macro-hangupcall") in new stack
    -- Executing [17772295467@from-pstn:8] Set("SIP/callcentric15-00000002", "__CALLINGPRES_SV=allowed_not_screened") in new stack
    -- Executing [17772295467@from-pstn:9] Set("SIP/callcentric15-00000002", "CALLERPRES()=allowed_not_screened") in new stack
    -- Executing [17772295467@from-pstn:10] Goto("SIP/callcentric15-00000002", "callingcard,7772295467,1") in new stack
    -- Goto (callingcard,7772295467,1)
    -- Executing [7772295467@callingcard:1] Answer("SIP/callcentric15-00000002", "") in new stack
    -- Executing [7772295467@callingcard:2] Wait("SIP/callcentric15-00000002", "1") in new stack
       > 0x7fb6e000da20 -- Probation passed - setting RTP source address to 204.11.192.163:50226
    -- Executing [7772295467@callingcard:3] AGI("SIP/callcentric15-00000002", "a2billing.php,1") in new stack
    -- Launched AGI Script /var/lib/asterisk/agi-bin/a2billing.php
<SIP/callcentric15-00000002>AGI Tx >> agi_request: a2billing.php
<SIP/callcentric15-00000002>AGI Tx >> agi_channel: SIP/callcentric15-00000002
<SIP/callcentric15-00000002>AGI Tx >> agi_language: en
<SIP/callcentric15-00000002>AGI Tx >> agi_type: SIP
<SIP/callcentric15-00000002>AGI Tx >> agi_uniqueid: 1440300079.14
<SIP/callcentric15-00000002>AGI Tx >> agi_version: 12.8.2
<SIP/callcentric15-00000002>AGI Tx >> agi_callerid: 12063700000
<SIP/callcentric15-00000002>AGI Tx >> agi_calleridname: 12063700000
<SIP/callcentric15-00000002>AGI Tx >> agi_callingpres: 0
<SIP/callcentric15-00000002>AGI Tx >> agi_callingani2: 0
<SIP/callcentric15-00000002>AGI Tx >> agi_callington: 0
<SIP/callcentric15-00000002>AGI Tx >> agi_callingtns: 0
<SIP/callcentric15-00000002>AGI Tx >> agi_dnid: 17772295467
<SIP/callcentric15-00000002>AGI Tx >> agi_rdnis: unknown
<SIP/callcentric15-00000002>AGI Tx >> agi_context: callingcard
<SIP/callcentric15-00000002>AGI Tx >> agi_extension: 7772295467
<SIP/callcentric15-00000002>AGI Tx >> agi_priority: 3
<SIP/callcentric15-00000002>AGI Tx >> agi_enhanced: 0.0
<SIP/callcentric15-00000002>AGI Tx >> agi_accountcode:
<SIP/callcentric15-00000002>AGI Tx >> agi_threadid: 140423827154688
<SIP/callcentric15-00000002>AGI Tx >> agi_arg_1: 1
<SIP/callcentric15-00000002>AGI Tx >>
    -- <SIP/callcentric15-00000002>AGI Script a2billing.php completed, returning 0
    -- Executing [7772295467@callingcard:4] Wait("SIP/callcentric15-00000002", "1") in new stack
    -- Executing [7772295467@callingcard:5] Hangup("SIP/callcentric15-00000002", "") in new stack
  == Spawn extension (callingcard, 7772295467, 5) exited non-zero on 'SIP/callcentric15-00000002'


Thanks!

**Comment by andres-moya** [comment]
This composer virus ask impossible things. 

-bash-4.1$ php ../composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/yaml v2.7.2 -> satisfiable by symfony/yaml[v2.7.2].
    - symfony/yaml v2.7.2 requires php >=5.3.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
  Problem 2
    - symfony/yaml v2.7.2 requires php >=5.3.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - phpunit/phpunit 4.7.7 requires symfony/yaml ~2.1|~3.0 -> satisfiable by symfony/yaml[v2.7.2].
    - Installation request for phpunit/phpunit 4.7.7 -> satisfiable by phpunit/phpunit[4.7.7].

Guys, centos 6 and PHP 5.3.3 is a good system, is it possible to download somewhere working tar that simply includes required vendor/autoload.php? What is symfony/yaml and why I need it? Is it PHP module? What is the last working version of A2Billing? This composer makes deployment platform dependant and too complicated. This is development tool, why not to package source code of VI and ED editors as dependency then ;) They are very useful editors ;) 

-bash-4.1$ php ../composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update



  [ErrorException]
  file_put_contents(./composer.lock): failed to open stream: Permission denied



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

Current folder is writable why not to create lock file?  Of course no way to run this virus as root.

**Comment by andres-moya** [comment]
Got it working. User that execute "update" and "install" should have rights to entire a2b tree. And it will forgive you not to have symfony/yaml even with PHP 5.3.9. I will tar it, if someone need it I can share ;)

**Comment by NogieGit** [comment]
Pls share. Edo.ekunwe@gmail.com

Thanks

Nogie Ekunwe
601.497.3932

**Comment by helsinki** [comment]
Hi, 
Yes, please share.
talsinki@gmail.com

Greetings

**Comment by rootious** [comment]
Hi andres-moya

Please share 
samy.battar@gmail.com

Kind regards

**Comment by hostile123** [comment]
I need help

email me that tar please krystian26@gmail.com

or how do I fix this?

[root@vodeoo a2billing]# php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package adodb/adodb-php could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
[root@vodeoo a2billing]# php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/yaml v2.7.2 -> satisfiable by symfony/yaml[v2.7.2].
    - symfony/yaml v2.7.2 requires php >=5.3.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
  Problem 2
    - symfony/yaml v2.7.2 requires php >=5.3.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - phpunit/phpunit 4.7.7 requires symfony/yaml ~2.1|~3.0 -> satisfiable by symfony/yaml[v2.7.2].
    - Installation request for phpunit/phpunit 4.7.7 -> satisfiable by phpunit/phpunit[4.7.7].

**Comment by chris001** [comment]
@Hostile it's telling you that it needs you to upgrade your PHP to 5.3.9 or newer
5.5 or 5.6 are the minimum recommended PHP versions now according to php.net the creators of PHP.  5.3.x and 5.4.x are past their end of life, no longer supported and discouraged to be used for security reasons.
Reference: http://php.net/supported-versions.php

**Comment by Mazuco** [comment]
This error continue again? I tried to use php 5.6 but this error continues see the log 

[Sun Jan 03 19:23:24 2016] [notice] Apache/2.2.22 (Debian) configured -- resuming normal operations
[Sun Jan 03 19:23:29 2016] [error] [client 192.168.25.100] PHP Warning:  require_once(/var/www/a2billing/common/lib/../../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/a2billing/common/lib/admin.defines.php on line 33
[Sun Jan 03 19:23:29 2016] [error] [client 192.168.25.100] PHP Fatal error:  require_once(): Failed opening required '/var/www/a2billing/common/lib/../../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/a2billing/common/lib/admin.defines.php on line 33
[Sun Jan 03 19:23:30 2016] [error] [client 192.168.25.100] PHP Warning:  require_once(/var/www/a2billing/common/lib/../../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/a2billing/common/lib/admin.defines.php on line 33
[Sun Jan 03 19:23:30 2016] [error] [client 192.168.25.100] PHP Fatal error:  require_once(): Failed opening required '/var/www/a2billing/common/lib/../../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/a2billing/common/lib/admin.defines.php on line 33
[Sun Jan 03 19:23:34 2016] [error] [client 192.168.25.100] PHP Warning:  require_once(/var/www/a2billing/common/lib/../../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/a2billing/common/lib/admin.defines.php on line 33
[Sun Jan 03 19:23:34 2016] [error] [client 192.168.25.100] PHP Fatal error:  require_once(): Failed opening required '/var/www/a2billing/common/lib/../../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/a2billing/common/lib/admin.defines.php on line 33

I use a Debian 7.9

**Comment by shalmon1** [comment]
Hi,
Very weird... I followed all instruction and got a perfectly running system - used it over a month now. Rebooted the server yesterday with no changes done...
and all of a sudden cannot access - get error 500 page and in error_log I see:
PHP Warning:  include(../lib/admin.defines.php): failed to open stream: No such file or directory in /var/www/html/a2billing/admin/Public/index ......

I tried to follow all solutions suggested but didn't succeed...

Any suggestions?

Ami

**Comment by pcdrob123** [comment]
Would be happy to take a look ?

**Comment by shalmon1** [comment]
Of course
How can I do that?

**Comment by pcdrob123** [comment]
When would you like me to take a look?

**Comment by shalmon1** [comment]
Whenever convenient to you. I am here...

This is absolutely related problem:

http://serverfault.com/questions/810782/fixing-path-issues-on-php-application

If I change the path manually in the file I can get the login screen again (but cannot pass it)

**Comment by pcdrob123** [comment]
What type of server are you running A2B on

**Comment by shalmon1** [comment]
Hosted VPS - installed with the FreePBX disto than a2billing.
It's centos 64bit 6.6
PHP 5.3.28
Asterisk 11.23.1

**Comment by pcdrob123** [comment]
How can you send me over vps details

**Comment by miken32** [comment]
This is a bug report, not a chat room or discussion forum. Take it somewhere else.

**Comment by pcdrob123** [comment]
Michael we are purely helping her to fix a A2b install. Isn't this page about the A2b issue in question.

**Comment by shalmon1** [comment]
Fixed it bro…
Created a soft link in /var/www/html/a2billing/admin/lib -->  /var/www/html/a2billing/common/lib. for some reason it lost all the links to ../common/lib
Looks OK now…

Thanks for help and support
