### ISSUE TITLE
Problem on A2Billing.php file or else

### ISSUE THREAD

**Issue by icaxis** [Star2Billing/a2billing#106]
Hello! Everyone I have read everything on the web. I have seen/read people that had/have the same issue as me. But no details on how they solve it or not.

I've installed A2billing 2.0.10. When I get incoming calls from DID (freePBX) it cannot get through A2Billing. It seems the file A2billing.php as an error. I just got busy signal and the call hangup.

[custom-a2billing]
exten => _X.,1,AGI(a2billing.php,1)
exten => _X.,n,Hangup

 -- Launched AGI Script /var/lib/asterisk/agi-bin/a2billing.php
    -- <PJSIP/XXXXXX-00000001>AGI Script a2billing.php completed, returning 0
    -- Executing [XXXXXXXXXX@custom-a2billing:2] Hangup

I try to put some real php error in the file, I even remove all the content nothing happen same result "returning 0".
All permissions are properly set, I have copied/linked "lib" folder close to the a2billing.php already.

I have found 2 threads in a forum similar, but nothing on how to solve this.
https://forum.asterisk2billing.org/viewtopic.php?f=33&t=10785
http://forum.asterisk2billing.org/viewtopic.php?f=33&t=10094

Is it a 2.010 problem.? Can somebody help me with this. I think turning nuts.

Thanks

**Comment by celangoni** [comment]
get the same problem, but I'm using version 2.1.1 as downloaded on a2billing site.

Testing the AGI code I think there is missing an include to adodb.
After getting composer[1] I made a symlink from vendor/adodb/adodb-php on common/lib (called adodb) and on line 49 at AGI/a2billing.php I added the following line:
include(dirname(__FILE__) . "/lib/adodb/adodb.inc.php");

Now is working!

Hope it help!

[1] https://github.com/Star2Billing/a2billing/issues/104 look for redge76 posts

**Comment by areski** [comment]
problem solved by https://github.com/Star2Billing/a2billing/commit/08020454cf9fa561db71b4d3e0b4a2d9785a5052

used v2.1.2

**Comment by areski** [comment]
please use v2.1.2

**Comment by realmali** [comment]
hi,

I have this same issue the above solution by areski doesn't slove my problem

I'm using A2Billing v2.1.4, Asterisk 11.16.0, FreePBX 12.0.76.1, centios 7
