### ISSUE TITLE
undefined function NewADOConnection()

### ISSUE THREAD

**Issue by Ara4Sh** [Star2Billing/a2billing#109]
Hello 
what is the problem 
mod_fcgid: stderr: PHP Fatal error:  Call to undefined function NewADOConnection() in /var/www/clients/client0/web14/web/a2b/common/lib/Class.A2Billing.php on line 3616

my php version :
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo

my a2billing.conf :
;
; A2Billing config file
; ---------------------

; Global Database Setup - select the database type and authentication as required.

[database]
hostname = localhost
port = 3306
user = DBUSER
password = "Password"
dbname = DBNAME
; dbtype setting can either be mysql or postgres
dbtype = mysql

i want to install only web interface of a2billing no need anything like asterisk modules . want to connect my backend server and my web interface with only mysql 
what is the problem ?

**Comment by Ara4Sh** [comment]
i thinks its because adodb is not present in common/lib in version 2.1.1 and you are using adodb in line of 3616 Class.A2Billing.php
so its 2 possibilities : 
1 if you stop using adodb why you call its function in Class.A2Billing.php
2 you forget to add adodb  in common/lib

**Comment by areski** [comment]
adodb is installed via php composer
https://github.com/Star2Billing/a2billing/blob/develop/INSTALL.rst#13-php-composer

On Tue, Jul 14, 2015 at 11:20 AM, Arash Shams <notifications@github.com>
wrote:

> i thinks its because adodb is not present in common/lib in version 2.1.1
> and you are using adodb in line of 3616 Class.A2Billing.php
> so its 2 possibilities :
> 1 if you stop using adodb why you call its function in Class.A2Billing.php
> 2 you forget to add adodb in common/lib
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Star2Billing/a2billing/issues/109#issuecomment-121177219>
> .
>



-- 
Kind regards,
/Areski

----
Arezqui Belaid, <areski@gmail.com>
Founder at Star2Billing (www.star2billing.com)

Tel: +34650784355
Twitter: http://twitter.com/areskib
LinkedIn: http://www.linkedin.com/in/areski

**Comment by Ara4Sh** [comment]
i installed a2billing web interface in an ispconfig account .  because of not conflicting the php packages installed by composer and the php packages installed by ispconfig im just move on to next step .

**Comment by ultratone** [comment]
​Try not to mix ISPConfig and A2billing within the same machine.​

--

UltraTone Sdn Bhd

*United States Office: *75 East Santa Clara Street, Suite P-80, San Jose,
95113

Phone: +1-408-715-2002

Fax:   +1-408-459-7766

Cell:  +1-818-910-2001


*Malaysia Office: *Unit 17A, Plaza Ampang City, No 332A Jalan Ampang,  KL,
50450

Phone: +60-3-2730-6404

Fax:   +60-3-48138823

Cell:  +60-12-3919138


*Websites: *UltraTone.com.my <http://www.ultratone.com.my/>


<http://www.ultratone.com.my/>

**Comment by Ara4Sh** [comment]
for some reasons i have no way but i thinks i finally can do it

**Comment by ultratone** [comment]
They are optimize to work under different PHP versions. You will also run
into socket and open file limitation when you have heavy web and call
traffic.

**Comment by Ara4Sh** [comment]
just ui is mix with ispconfig - i have a backend server that run a2billing and astersik connected to fronted with remote database 
thank you very much for help and opinion
