### ISSUE TITLE
php errors after a3billing upgrade to 2.1.1

### ISSUE THREAD

**Issue by ccguerrero** [Star2Billing/a2billing#110]
yesterday after upgrade from 2.0.11 to 2.1.1 to try to fix issues in currencies with yahoo finance i got the following errors.

    [Tue Jul 14 00:48:19 2015] [error] [client xxx.xxx.xxx.xxx] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/common/lib/Misc. php on line 1290

i had to change line 1290 on Misc.php to:
`$base_value = explode(',', $line_base_value);`

This gives a blank page, had to remove the [1] at the end, i don't know if this is correct, because i'm not a programmer but just wanted a2billing to work.

then got this error in the same file

     [Tue Jul 14 01:33:57 2015] [error] [client xxx.xxx.xxx.xxx] PHP Parse error:  syntax error, unexpected ';' in /usr/src/a2billing/common/lib/Misc.php on line 1302

Had to modify again line 1302, to add a ")" and remove [1], again this just to make a2billing to work.

Finally, a2billing worked, but currencies couldn't been update anyway, with error:

### The base_currency is too small. Currency update ABORTED!

just before upgrade a2billing, i upgraded php fom 5.3.3.40 to php 5.3.3.46, do you think this may be a problem?

**system info**
* CentOS release 6.6 (Final)
* Linux  2.6.32-431.1.2.0.1.el6.x86_64
* x86_64

* PHP 5.3.3 (cli) (built: Jul  9 2015 17:39:00) 
  Copyright (c) 1997-2010 The PHP Group
  Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

* Asterisk 11.13.0

Any sugestion would be appreciated.

Regards,

**Comment by areski** [comment]
when do you get this error? only when you try to update the currency?

**Comment by ccguerrero** [comment]
the two errors appear just to try to access the login screen for  a2billing,
they disappear after i mad the changes i stated. everything seems to work correctly, but i'm unable to update currency. I don't know where to look for errors.

I can give you access to the server if you are interested.

Regards,

**Comment by areski** [comment]
this might solve the problem https://github.com/Star2Billing/a2billing/commit/67b70464151d1cb6dc7881f2bf6d1a00549d3000

**Comment by ccguerrero** [comment]
That fixed the issue.
I can confirm currencies are updated correctly.

regarss,

**Comment by miken32** [comment]
As this requirement is a fairly big change, it might be worthwhile putting a check in place, so that if autoload.php can't be included, it shows an error message. Over the last few years I think everyone is used to just untarring over the old version and updating the database.

**Comment by jacgsaw** [comment]
Para este error configure manualmente la moneda predeterminada en 1.00000, y las monedas que requiera por lo general son dos o tres las configuras manual, y veras que ahora las recargas funcionan correctamente.
