### ISSUE TITLE
Fatal error  SmartyFactory

### ISSUE THREAD

**Issue by afshin-blue** [Star2Billing/a2billing#111]
first receive this 2 error PHP Parse error:  syntax error, unexpected '[' in /var/www/html/a2billing/common/lib/Misc.php on line 1290
PHP Parse error:  syntax error, unexpected '[' in /var/www/html/a2billing/common/lib/Misc.php on line 1302
remove [1]
then got this error
PHP Fatal error:  Class 'Factory\\SmartyFactory' not found in /var/www/html/a2billing/common/lib/admin.smarty.php on line 43

**Comment by areski** [comment]
Install the last version v2.1.2 this should be ok there

**Comment by areski** [comment]
https://github.com/Star2Billing/a2billing/commit/67b70464151d1cb6dc7881f2bf6d1a00549d3000

**Comment by afshin-blue** [comment]
Dear areski i install v2.1.2  still got blank page. i use both SVN and zip file
first error: PHP Fatal error:  require_once(): Failed opening required '/var/www/html/a2billing/common/lib/../../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/a2billing/common/lib/admin.defines.php on line 33

i download vendor with composer then copy to a2billing folder got second error
PHP Parse error:  syntax error, unexpected '[' in /var/www/html/a2billing/common/lib/Misc.php on line 1306
then i remove [1] and last error as before:
PHP Fatal error: Class 'Factory\SmartyFactory' not found in /var/www/html/a2billing/common/lib/admin.smarty.php on line 43

i thin this 2 line need to be fix because file is located there and path is not correct
define( 'FULL_PATH', dirname(__FILE__) . '/' );
define( 'SMARTY_DIR', FULL_PATH . '../../vendor/smarty/smarty/libs/' );

**Comment by areski** [comment]
@afshin-blue as per the patch I sent earlier this needed to be included to work. Now to make it more easy for you to test, I just released v2.1.3
