### ISSUE TITLE
Error upgrading to version 2.1 on file common/lib/agent.smarty.php on line 82 

### ISSUE THREAD

**Issue by ccguerrero** [Star2Billing/a2billing#112]
When upgrading to version 2.1 i got this error

`[error] [client 187.191.10.16] PHP Parse error:  syntax error, unexpected '[', expecting ')' in /usr/src/a2billing/common/lib/agent.smarty.php on line 82`

and on file common/lib/agent.smarty.php on line 82 i found this

`getpost_ifset(['section']);`

and I'm pretty sure it should be

`getpost_ifset('section');`

Regards,

**Comment by areski** [comment]
getpost_ifset is a function that expect an array:
""""
function getpost_ifset($test_vars)
{
    if (!is_array($test_vars)) {
        $test_vars = array (
            $test_vars
        );
    }
""""
