### ISSUE TITLE
Acess denied

### ISSUE THREAD

**Issue by vivek779** [Star2Billing/a2billing#113]
hello I installed the a2billing for the first time it get installed  and i  authenticate with default username and password 
 .When I tries to click any link on the page it shows  "sorry you dont have acess to this page"  can you please guide me what mistake i am doing i can attach screenshot if you need

**Comment by sujithar37** [comment]
It might be issue with apache access. Apply the correct web permission to the directory /var/lib/php/session . for example, if the web username and group is apache then apply the permission to the folder with the below command

chown -R apache. /var/lib/php/session

Also check the httpd error log before proceeding anything. Most probably the permission will resolve the existing issue

**Comment by vivek779** [comment]
thnaks for the revert it works perfactly now thank u
