### ISSUE TITLE
How to configure a2billing  to track sip calls

### ISSUE THREAD

**Issue by vivek779** [Star2Billing/a2billing#114]
Hi i am new here in this field don't have depth knowledge 
just installed a2billing   on v.p.s
i wanted to see call tracking in a2billing of sip clients for testing purpose
so i created 2  sip clients on asterisk server   with their extensions 1234 and 1235 on the same vps
and initiated the calls with zoiper softphone.
How would i configure a2billing to see tracking of these 2 clients calls
can anyone  please guide me how to do this  i tried to find it  bt  unable to understand it 
if anyone please guide me it would be helpful

**Comment by pecuna** [comment]
You have to create sip accounts from A2Billing. You first create 2 accounts and click
"CREATE SIP CONFIG  Yes" on their config.   After saving you go to Custommers -> Voip Settings and click Add Sip Config. Fill the data, save and click Generate new sip conf and after that click 
"Click here to reload your asterisk server". Now you can try to log them on your zoiper softphone.
