### ISSUE TITLE
Paypal  payment not coming in A2billing 

### ISSUE THREAD

**Issue by gudge25** [Star2Billing/a2billing#115]
1-Log from PAypal  (Instant Payment Notification (IPN) details)
HTTP response code
200

Delivery status
Sent

No. of retries
1

Transaction ID
7EB28396BW929134Y

transaction_subject=&payment_date=02:51:41 Sep 10, 2015 PDT&txn_type=web_accept&last_name=&residence_country=UA&item_name=Asterisk Technology&payment_gross=5.00&mc_currency=USD&business=satskiy.a@gmail.com&payment_type=instant&protection_eligibility=Ineligible&verify_sign=AyPYlQ8Oa6oGsLhFw3LOipLJYfWnAoEfClutMmrgx7eqdEzsMhv2UJCp&payer_status=unverified&tax=0.00&payer_email=info@asterisk.biz.ua&txn_id=7EB28396BW929134Y&quantity=1&receiver_email=satskiy.a@gmail.com&first_name=&payer_id=3N9SJYCPDJFQG&receiver_id=NN8XJS9XEP22C&item_number=&handling_amount=0.00&payment_status=Completed&payment_fee=0.52&mc_fee=0.52&shipping=0.00&mc_gross=5.00&custom=&charset=windows-1250&notify_version=3.8&ipn_track_id=220ee8bc52900

2-Log from web server 
173.0.81.1 - - [10/Sep/2015:12:51:51 +0300] "POST /customer/checkout_process.php?transactionID=6&sess_id=4cqac5rp05au80rg038kbs6fs0&key=71748fcddd1200ffc710b1d97b778dc4 HTTP/1.0" 500 -
173.0.81.1 - - [10/Sep/2015:12:52:03 +0300] "POST /customer/checkout_process.php?transactionID=6&sess_id=4cqac5rp05au80rg038kbs6fs0&key=71748fcddd1200ffc710b1d97b778dc4 HTTP/1.0" 200 -

3-A2Billing v2.1.0

**Comment by gudge25** [comment]
update
- i can see in the payment log 
2015-09-10 12:50:46 	paypal 	In Process 		5.000 	18 	4790053494
SO the question is 
1- why the payment is not added automatically --it freeze   in Process? 
2- i hawe in the settings "charge_paypal_fee ->No"   why there is no fee on a customer account (maybe i am wrong)
Thanks

**Comment by areski** [comment]
you might want to test with this version, I wrote last night: https://gist.github.com/areski/34d885835ce6d3d48526
It reflects the last integration advices from paypal for IPN.
Make a backup copy of checkout_process.php before testing it.

**Comment by areski** [comment]
Ignore the previous message, I pushed some changes here: https://github.com/Star2Billing/a2billing/commit/aae22472bc4d94087f20ded7672154be63513698 which just has been successfully tested
