### ISSUE TITLE
username=s

### ISSUE THREAD

**Issue by gudge25** [Star2Billing/a2billing#118]
i use real-time 
and after sip account registers on my server
i see 
username=s 

![screenshot from 2015-10-30 18 42 08](https://cloud.githubusercontent.com/assets/2346208/10852070/707a5dba-7f37-11e5-8af2-cd0c02456bba.png)
![screenshot from 2015-10-30 18 46 44](https://cloud.githubusercontent.com/assets/2346208/10852069/7078a4fc-7f37-11e5-8e48-7f65e4560235.png)

**Comment by areski** [comment]
We can read the url, you should consider deleting this.

**Comment by gudge25** [comment]
ok no prob

**Comment by gudge25** [comment]
any news?
is it possible to solve?

**Comment by areski** [comment]
Regarding your issue: https://forum.asterisk2billing.org/viewtopic.php?f=34&t=8989
You might want to play with:

```
rtupdate=yes ; Send registry updates to database using realtime? (yes|no)
; If set to yes, when a SIP UA registers successfully, the ip address,
; the origination port, the registration period, and the username of
; the UA will be set to database via realtime.
; If not present, defaults to 'yes'. Note: realtime peers will
; probably not function across reloads in the way that you expect, if
; you turn this option off.
```
