### ISSUE TITLE
SQL Query locked DB

### ISSUE THREAD

**Issue by levageneral** [Star2Billing/a2billing#132]
Some time my a2billing down, I detected that on this moment DB locked. 
command full processlist and saw this query locked DB 
Status: User sleep 
info: SELECT username,useralias,UNIX_TIMESTAMP(creationdate) creationdate,vat,firstname,lastname FROM cc_card WHERE id = 1 OR SLEEP(5)

I runned this queary manually and DB also locked.
I didn't find this query in a2billing scripts. I dont understand why need SLEEP(5) in this query and where located file with this script. 

Please, can someone help me with my issue.

**Comment by areski** [comment]
This query is not part of the a2billing codebase
