### ISSUE TITLE
Sort DIDs by DID, not by DID ID.

### ISSUE THREAD

**Issue by gromm** [Star2Billing/a2billing#15]
This issue is more of an interface bug than anything. 

In Inbound DID->Destination->Add Destination, when our DID database contains hundreds of DIDs, it is far more useful to sort DIDs by the DID than it is to sort by DID, then the DID's database ID (mostly chronological order when entering them into the DB). The reason for this is that typing in the entire 10+ digit DID to find it in the list can be tremendously laborious, especially when it has to be re-done several times because the browser timeout for doing so is too short. Typing the first 7 numbers gets the user to the general area in the list where they can find the rest of the DID.

The fix is easy. In /a2billing/admin/Public/form_data/FG_var_did_destination.inc, find the code block starting with: 

$HD_Form -> AddEditElement (gettext("DID") 

(Near line number 135 of this file) Then change the "order by" field from "did, id" to "did". In the code in this particular place, the "order by" field is number 9, although I know for certain that the '$value' field is data for several different variables in $HD_Form, so this may change in the future.

**Comment by arb50** [comment]
This issue still remains. I have version 2.0.16 and the DIDs do not sort by DID. Also when importing DIDs in CSV file, the additional fields do not work and I am unable to change the billing type. I have to do this manually at this time for hundreds of DIDs.

How can this be fixed?
