### ISSUE TITLE
SIP account is not created in asterisk

### ISSUE THREAD

**Issue by Alucardroot** [Star2Billing/a2billing#180]
Hi everyone
recently started learning a2 and stumbled upon a problem
when I create a sip user in my billing account
with login and password
I couldn't register them in my softphone
then, nevertheless, I went into the asterisk cli and saw that it did not have any users at all
but they are in mysql database
please tell me how to fix this

sorry for asking a stupid question :)
tnx

**Comment by voztovoice** [comment]
To see if the sip account is correctly created, from asterisk console:

CLI> sip show peer NumberExtension load

and when your try to register you have to look if there is any error in Asterisk Console.
