### ISSUE TITLE
A2Billing 2.1 still with bug on A2B_entity_friend.php?form_action=ask-edit&atmenu=sip

### ISSUE THREAD

**Issue by ale-trevizoli** [Star2Billing/a2billing#96]
Hi. We upgrade from 2.0.16 to 2.1 because since 2.0.16 have bug on Add and Edit of Voip Settings (SIP).
SetVar field don't accept '=' character and if you put example test=1 on that field after save it became test1.
Another bug since 2.0.16 is after post it's return to wrong place. Instead it return to admin/Public/A2B_entity_friend.php?atmenu=sip&section=1
it goes to admin/Public/A2B_entity_friend.php showing IAX list instead.

Our main ploblem is with SETVAR because we use it to set local code area for our customers. If you have something to help us please advice.

Thanks!

**Comment by areski** [comment]
you could comment this line, but you will expose to some security issue https://github.com/Star2Billing/a2billing/blob/develop/common/lib/Misc.php#L290

**Comment by ale-trevizoli** [comment]
Areski thank you.
Another bug is when we click on save form on VOIP Settings(SIP-when we are editing) it's come back to wrong place (IAX) settings. Is possible to resolve it?
Thanks again!
