### ISSUE TITLE
restriction easy faked by using speeddial

### ISSUE THREAD

**Issue by arheops** [Star2Billing/a2billing#97]
so
in Class.A2Billing.php at line near 906 you are dooing following:

1) check restricted number.
2) if check not success, change speeddial  to any number(so restriction will not be checked after that)

solution:
swap sections, put speeddial substitute BEFORE restriction check.

bugs seams vital )

**Comment by areski** [comment]
Thanks! 
Fixed with https://github.com/Star2Billing/a2billing/commit/a40e37fefef7ab85999d04298b6e582b41930e7e
